### ISSUE TITLE
[Classic] Addon compatibility?

### ISSUE THREAD

**Issue by qiazee** [Pierre-Sassoulas/grey-handling#2]
Hey and thank you for your great addon!

Is your Classic addon compatible with just the default bags or with other "bag addons" currently compatible with WoW Classic, like [Inventorian](https://www.curseforge.com/wow/addons/inventorian) (which I will use), [OneBag3 Classic](https://www.warcrafttavern.com/addons/onebag3-classic/) or [ArkInventory Classic](https://www.curseforge.com/wow/addons/ark-inventory-classic)?

I would love to use it but is it means using default bags, it's a no-go for me.

Can you specify the compatibility of your addon in the description? 😄 

EDIT: adding the Classic tag.

**Comment by Pierre-Sassoulas** [comment]
It's not entirely compatible with ArkInventory for now (0.1.0). I think they broke the API for making items glow by bag id and slot id. I don't know about the two others. I can try on retail, this evening.

What will work whatever the addons you have:
* Picking cheapest item when there is only one to throw or exchange in one click
* Announcing the cheapest grey in chat
* Text explanation of what the two cheapest items are in chat

What is not working in ArkIventory as of (0.1.0) :
* Orange glowing items in a bag when there are two cheapest items (You will have to read the explanation, and it's... annoying fast, but still better than nothing)

I plan to do ArkInventory at least because I and some of my guildies are using it. But there is a lot of things to do before august the 27th, and I'm very new to wow addons. I kinda wanted to make #3 , How do you think I should priorize ?

**Comment by qiazee** [comment]
A lot of things seem to work well whatever our addons, so it's fine, no need to prioritize this issue (especially since Classic is coming out soon, I'm sure other things are more important, like #3).

The only main issue is the lack of mention of what's not working with the main bag addons. If you list these incompatibilities, you can take your time implementing fixes later. 😉 

Another question, off-topic with this problem: I plan to use [Better Vendror Price](https://www.curseforge.com/wow/addons/better-vendor-price), so your addon feature that allows to display item prices will be a "duplicate". Is it possible to disable this feature so that prices are not displayed twice? Should I open a new issue for this?

Thanks a lot for your answer.

**Comment by Pierre-Sassoulas** [comment]
Good point, I could try to work better with better vendor price. There is already an (undocumented, because I did it during lunch break today :D) option to hide price. It would work well if you have an addon that handles price everywhere, but it's probably going to get old really fast if you have to remove it and put it back all the time. Don't hesitate to open an issue if removing all item tooltip for item does not fix your problem :)

**Comment by qiazee** [comment]
Okay, very nice! I'm closing this issue for now, and I'll open a new one if necessary.

I'm also French by the way, and I noticed that some sentences in English are too literal in the addon options. I'll submit a pull request tomorrow to improve some wording.

Thank you again for your all answers, and thank you for this addon!

**Comment by Pierre-Sassoulas** [comment]
https://github.com/arkayenro/arkinventory/issues/1193 permitted to make the ArkInventory integration properly. OneBag3 is working too. I tried to do Inventorian too but I'll probably need to ask the developer too.

**Comment by qiazee** [comment]
Wow, I read your discussion, it's really nice! Thanks for taking care of this!
